export const env ={
    baseUrl:"http://localhost:8089/SpringMVC",
    GetAllEventUrl:"/Event/getallEvent",
    DeleteEventUrl:"/Event/delete/",
    AddEventUrl:"/Event/add",
    UpdateEventUrl:"/Event/update",
    GetOneEventUrl:"/Event/getOneEvent/",
    GetFavEventUrl:"/Action/getallFavEvent/",
    GetFavActionUrl:"/Action/getFav/",
    GetLikeActionUrl:"/Action/getLike/",
    GetJoinActionUrl:"/Action/getJoin/",
    GetCommentActionUrl:"/Action/getAllComment/",
    GetInviteActionUrl:"/Action/getInvite/",
    GetOneActionUrl:"/Action/getOneAction/",
    GetAllActionUrl:"/Action/getallAction/",
    DeleteOtherActionUrl:"/Action/delete/",
    RefuseInviteActionUrl:"/Action/refuse/",
    AcceptInviteActionUrl:"/Action/accept/",
    addActionUrl:"/Action/add/",

    }