export const env ={
    baseUrl:"http://localhost:8089/SpringMVC",
    GetFeedbackUrl:"/FeedBack/getsent",
    AddUrl:"/FeedBack/add",
    feedsRecievedUrl:"/FeedBack/show/",
    nbrRecievedUrl:"/FeedBack/nbr",
    getusersurl:"FeedBack/getusers",
    getPosturl :"/post/get",
    getCommentByPost:"/comment/getComments/",
    updatePosturl:"/post/update/",
    addPostWithoutPhoto:"/post/addPostWithoutPhoto",
    signlerPostUrl :"/post/Signale/",
    getMemoriesUrl :"/post/getMemories/1",
    updatePostUrl:"/post/update/1",
    likePostUrl:"/post/1/like/",
    dislikePostUrl:"/post/1/dislike/",
    removeLike:"/post/1/remove/",
    
    //--------- forum ------------
    addArticleUrl :"/forum/addarticle/1",
    deleteArticleUrl :"/forum/delete/",
    updateArticleUrl :"/forum/update/",
    getAllAriclesUrl :"/forum/getatricles",
    rateForum:"/forum/rate/1/",
    getOneAtricle:"/forum/getOneAtricle/",
    similarArticle:"/post/similare/1",
    //---------favorite forum ------------//
    addArticleTofavoritesUrl:"/forum/addtof/1/",
    getFavoritesArticlesUrl :"/forum/getFavoiritesArticles/1",
    rateArticleUrl :"/forum/rate/1/",
    //---------tags-----------------//
    gettagsByArticle :"/forum/gettagsbyArticle/",
    getTagsUrl :"/forum/gettags",
    getDetails:"/forum/getTagDetails",
    getTagArticles:"/forum/getatriclesbyTag/",
    getOneArticle:"/forum/getOneAtricle/",
    //---------comment--------------//
    addCommentUrl:"/comment/addComment/",
    likeCommentUrl:"/comment/makelikecomment/1/",
    updateCommentUrl:"/comment/updatecomment/",
    deleteComentUrl:"/comment/deletecomment/",
    deleteLikeUrl:"/comment/deleteLike/1/",
    addCommentToComment:"/comment/addCommentToComment/",
    GetCommentOfComment:"/comment/GetCommentOfComment/",
    //------------opinion----------------
    getOpinionByArticle:"/opinion/getOpinionbypost/",
    addOpinion:"/opinion/add/",
    deleteOpinion:"/opinion/delete/",
    updateopinion:"/opinion/update/",
    upUrl:"/opinion/up/",
    downUrl:"/opinion/down/",
      //------------opinion----------------
      userbirthday:"/user/BirthFriends",
//**********haifa********* */
getBadge:"/Evaluation/getbadge/",
getTrophies:"/Evaluation/gettrophies/",
gettropheytoday:"/Evaluation/gettropheytoday/",
getnbrRecieved:"/FeedBack/nbr/",
getfeedsSent:"/FeedBack/show-sent/",
getusers:"/FeedBack/getu",
getnbrSent:"/FeedBack/nbrsent/",
getusersnames:"/FeedBack/getun",
getusersBadges:"/Evaluation/getUsersBadges",
getBadgePoints: "/Evaluation/getbadgesvaluesmax",
getevents:"/Evaluation/gettauxevent",
gettauxevent:"/Evaluation/gettauxevent",
gettauxf:"/FeedBack/tauxf"
    }