export const env ={
    baseUrl:"http://localhost:8089/SpringMVC",
    GetFeedbackUrl:"/FeedBack/getsent",
    AddUrl:"/FeedBack/add",
    feedsRecievedUrl:"/FeedBack/show/",
    nbrRecievedUrl:"/FeedBack/nbr",
    getusersurl:"FeedBack/getusers",
    getPosturl :"/post/get",
    getCommentByPost:"/comment/getComments/",
    getBadge:"/Evaluation/getbadge/",
    getTrophies:"/Evaluation/gettrophies/",
    gettropheytoday:"/Evaluation/gettropheytoday/",
    getnbrRecieved:"/FeedBack/nbr/",
    getfeedsSent:"/FeedBack/show-sent/",
    getusers:"/FeedBack/getu",
    getnbrSent:"/FeedBack/nbrsent/",
    getusersnames:"/FeedBack/getun",
    getusersBadges:"/Evaluation/getUsersBadges",
    getBadgePoints: "/Evaluation/getbadgesvaluesmax"
    }